/*******************************************************************************
 * PathVisio, a tool for data visualization and analysis using biological pathways
 * Copyright 2006-2022 BiGCaT Bioinformatics, WikiPathways
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************/
package org.pathvisio.core.data;

/**
 * A result generated by ECOQuery, and obtained from ECOQuery.getResult This
 * contains information about a ECO record, such as term.
 * 
 * @author finterly
 */
public class ECOResult {
	private String id;
	private String term;

	public String getId() {
		return id;
	}

	void setId(String id) {
		this.id = id;
	}

	public String getTerm() {
		return term;
	}

	void setTerm(String term) {
		this.term = term;
	}

}
